### ISSUE TITLE
1 DEAT Y

### ISSUE THREAD

**Issue by tronsmit** [JustCarmen/fancy_privacy_list#6]
I have individuals with a 
1 DEAT Y 
record, (without a death date record, and date of death=110y less than the 120y limit), privacy_list is showing them as alive and therefore hidden from visitors, while I can see them when I browse my site without logging in.

Is this normal?

**Comment by JustCarmen** [comment]
The webtrees way is the right way. When a person is recorded death, the 120 years limits isn't taken into account anymore.
